SURIVALGAMES:
  CONFIG:
    PREFIX: '&8[&aSurvivalGames&8]'
    FALLBACKSERVER: Lobby
    MIN_PLAYERS: 2
    MAX_PLAYERS: 8
    MOTD:
      LOBBY: '&aLobby'
      FULL_LOBBY: '&6Lobby'
      INGAME: '&4Ingame'
      RESTART: '&cRestart'
    COUNTDOWN:
      LOBBY: 61
      SPAWN: 6
      RESTART: 15
      DEATHMATCH: 61