SURIVALGAMES:
  CONFIG:
# Select Languages from (en_EN , de_DE)
    LANGUAGE: en_EN
    PREFIX: '&8[&aSurvivalGames&8]'
    FALLBACKSERVER: Lobby
    MIN_PLAYERS: 2
    MAX_PLAYERS: 8
    MOTD:
      LOBBY: '&aLobby'
      FULL_LOBBY: '&6Lobby'
      INGAME: '&4Ingame'
      RESTART: '&cRestart'