name: SurvivalGames
version: 1.0
author: Snx

main: de.snx.survivalgames.SurvivalGames
commands:
  surivalgames:
    aliases: [sg]
    permission: survivalgames.help
    description: show all sg commands