name: SurvivalGames
version: 1.0
author: Snx

main: de.snx.survivalgames.SurvivalGames

commands:
  survivalgames:
    aliases: [sg, game, start]
    permission: survivalgames.help
    description: show all sg commands