name: SurvivalGames
version: 1.0
author: Snx

main: de.snx.survivalgames.SurvivalGames

commands:
  survivalgames:
    aliases: [sg]
    permission: survivalgames.admin
    description: show all sg commands